### ISSUE TITLE
When using the Registration App: Group assignment done on creation even it is disabled

### ISSUE THREAD

**Issue by xbluemonkx** [stjosh/auto_groups#59] opened 2021-11-20 18:02 UTC
Hi,

https://github.com/stjosh/auto_groups/issues/57 is not working for me as intended.

Current Situation:
- Apps: Autogroup + Registration + Talk
- Setup: There is a Group "All" that was invited to a Chat "Groupchat"
- Settings 1: Autogroup has not set the checkbox 1 (on creation) but set 2 + 3 (editing + login)
- Settings 2: Registration app is set to wait for confirmation / activitation by admin before a user can login

Current Behavior:
- User creates an account
- Groupchat shows a message "guest has added [users name] to chat
- looking into user management I can see that the user was inded auto-added to group "All"

Intended Behavior:
- User is NOT auto-assigned to any group unless the user was edited by the admin or logs in the first time

**Comment by xbluemonkx** [comment] 2021-11-20 18:08
Furter testing showed:
- if a user is created by an admin the user is indeed not added to any group automatically ==> that is good, i guess
- editing of the user (e.g. changing the name or the quota) done by an admin does not add him to a group ==> guess this is not good

**Comment by stjosh** [comment] 2021-11-22 10:37
Hmm, I'm sorry to hear that. A few first quick thoughts:

- I'm glad to hear that it at least works when the user is added by an Admin - that was actually the use-case I had primarily tested. I assumed that the same things do happen when the user is created with the "Registration"-app - seems my assumption was wrong. 😞 
- You're noticing that changing the user by an admin (changing the name and/or quota) does not alter the groups. That's correct insofar that the AutoGroups app does only get into action if the _groups_ of a user has been edited (assuming that there's no reason to double-check the groups otherwise). Does that make sense, or is it counter-intuitive somehow?

**Comment by stjosh** [comment] 2021-11-22 10:38
I will see whether I can find out what's different when using the Registration app as opposed to an admin creating users. Any hints/help here would be highly appreciated, as I do not personally use the Registration app.

**Comment by stjosh** [comment] 2021-11-22 10:54
I think the problem is here in the Registration App: 

https://github.com/nextcloud/registration/blob/3c12acfa5dc764b5d05ef116d6df0cc4b32b2176/lib/Service/RegistrationService.php#L417

I.e., even if Admin Approval is required, after creating the new user (which will _not yet_ assign the Auto Group), the "Registered User Group" configured in the Registration App is set. This triggers the "UserAddedEvent", which is caught by the "Auto Groups" app and then assigns the Auto Group.

The "admin approval" functionality only comes on line 425-428 (and it simply disabled the user).

Thus, may I ask you @xbluemonkx to check the following on your installation:

- Do you have anything configured in the Registration App's "Registered User Group"?
- If yes (which I assume): What happens if you remove any group there or disable this feature? Does the "Auto Groups" app then work correctly in your workflow?

As the "Registered User Group" feature by "Registration" is somewhat overlapping with the functionality "Auto Groups" provides, I think there's no scenario where this should be used if "Auto Groups" is installed besides "Registration".

Looking forward to your feedback!

**Comment by xbluemonkx** [comment] 2021-11-22 12:00
Hi,

1) it absolutely makes sense, that "check on change" only checks in case of group-changes. Would probably make the description a little more precise here.
2) You are absolute right and I am a little ashamed that I did not notice that before (or that i did not remember it): the regstration app has a setting: default group. this assigns the new user to a group.
3) so what would solve the isse was I remove the default group from registrations, but this means I would have to add the group manually after activating the new user or wait until he logs  in the first time.
4) ideal would be if there was another trigger for autogroups: check on activation of user.

**Comment by stjosh** [comment] 2021-11-22 12:55
Honestly, I am hesitant to add yet another hook - simply because the number of options to enable/disable should not be too big IMHO - just to keep things simple to administer. With every hook we add, the number of possible combination of enabled/disabled hooks grows exponentially and with this the chance that there will be one or the other "strange" combination of settings producing unexpected behavior.

Furthermore, there is a complication: As you saw in the code linked above, the Registration app _first_ assigns the Default Group and _only then_ disables the user in case admin approval is required. Therefore, even if I added this hook, the group assignment to the Default Group would already have been done (and the Auto Group assigned as well) even before the user account is disabled. Basically, this is already an example of unexpected behavior I have mentioned just above - the order in which the events appear is not at all controlled by my app for this and most probably also for other cases.

From my point of view, what would actually "save" you is to disable the option currently labelled "Check Auto Group membership on user modification." (I will make this more precise as by your proposal, see #60) and check the "Check for correct Auto Group membership on every login."-option. With this change, my app will not assign the AutoGroups when the Registration App sets its "Default Group" (and also not when an admin activates the account!), but only when the user logs in for the first time (and on every subsequent login). The backside of this approach is that an admin can temporarily (by accident) remove a user from the AutoGroups and it is only corrected on the user's next login. However, this might be outweighed by the advantages of having the AutoGroups assigned automatically.

But, taking one step back: Why do you even need the Registration-App's "Default Group" when you use the "Auto Groups" in parallel? Wouldn't it also solve your issue if you just added the respective group to the list of Auto Groups and remove it as Default Group from the Registration app? Or, asked the other way round: Why do you even need the AutoGroups app if there's already the Registration app's handy "Default Group" feature?

**Comment by xbluemonkx** [comment] 2021-11-22 14:13
Hi,
I aggree with you that adding another hook is probably not a good idea.

You are really asking good questions here. I think i added the autogroup app, to make sure that noone is accidently removed from the "all" group.

And I used default group from registration to not forgett adding someone to the "all" group once i activated him.

But getting one step back if probably the right thing to do here. I guess I need to rethink my process.

sorry for causing confusion. I think making the hooks mutual exclusive was a good idea anyway so I hope you are not too angy with me :)

**Comment by stjosh** [comment] 2021-11-22 15:28
@xbluemonkx I'm not angry at all, no worries 😄 Just trying to understand whether this is actually an interesting use-case to follow-up on or not. And I agree, your proposal in #57 was absolutely worthwile to do anyway!

I'm closing this issue for the moment - feel free to re-open in case you come to the conclusion that your scenario still requires an extension that is not yet covered and might be beneficial for other users as well.

**Closed by stjosh** 2021-11-22 15:28 UTC
Labels: bug, question
